io.jmix.core.DevelopmentException: Unable to find an instance of type 'class io.jmix.ui.action.list.CreateAction' after designer-based creating screen was opened #20
(cherry picked from commit 597ba995e9ec02b2c73b26f4961bc6507e713ed4)